import type {CSSProperties} from 'react';

/** Shared styles for ProviderSettingsCard — extracted to keep component under 400 lines. */
export const styles: Record<string, CSSProperties> = {
  card: {
    background: 'var(--surface-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '12px',
    padding: '0',
    maxWidth: '600px',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid var(--border-color)',
    background: '#252525',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  title: {
    margin: 0,
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--primary-text-color)',
  },
  subtitle: {
    margin: 0,
    fontSize: '0.75rem',
    color: 'var(--secondary-text-color)',
    marginTop: '2px',
  },
  saveBtn: {
    background: 'var(--accent-color)',
    border: 'none',
    color: 'white',
    padding: '6px 14px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 500,
    fontFamily: 'inherit',
  },
  savedBtn: {
    background: '#34A853',
    border: 'none',
    color: 'white',
    padding: '6px 14px',
    borderRadius: '6px',
    cursor: 'default',
    fontSize: '0.8rem',
    fontWeight: 500,
    fontFamily: 'inherit',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  activeBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 20px',
    fontSize: '0.75rem',
    color: 'var(--accent-color)',
    background: 'rgba(138, 180, 248, 0.08)',
    borderBottom: '1px solid var(--border-color)',
  },
  activeDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: '#34A853',
  },
  providerList: {
    display: 'flex',
    flexDirection: 'column',
    padding: '16px 20px',
    gap: '12px',
  },
  providerRow: {
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    overflow: 'hidden',
    transition: 'border-color 0.2s',
  },
  providerHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 12px',
    background: 'rgba(255,255,255,0.02)',
  },
  providerHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flex: 1,
  },
  radioBtn: {
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    border: '2px solid var(--accent-color)',
    cursor: 'pointer',
    padding: 0,
    flexShrink: 0,
  },
  nameInput: {
    background: 'transparent',
    border: 'none',
    color: 'var(--primary-text-color)',
    fontSize: '0.9rem',
    fontWeight: 500,
    fontFamily: 'inherit',
    flex: 1,
    outline: 'none',
    minWidth: 0,
  },
  providerActions: {
    display: 'flex',
    gap: '4px',
  },
  iconBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--secondary-text-color)',
    cursor: 'pointer',
    padding: '4px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    fontFamily: 'inherit',
  },
  fields: {
    flexDirection: 'column',
    gap: '12px',
    padding: '0 12px 12px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  label: {
    fontSize: '0.75rem',
    color: 'var(--secondary-text-color)',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  input: {
    background: 'var(--background-color)',
    border: '1px solid var(--border-color)',
    borderRadius: '6px',
    padding: '8px 10px',
    color: 'var(--primary-text-color)',
    fontSize: '0.85rem',
    fontFamily: "'Space Mono', monospace",
    width: '100%',
    boxSizing: 'border-box',
  },
  keyInputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  eyeBtn: {
    position: 'absolute',
    right: '8px',
    background: 'none',
    border: 'none',
    color: 'var(--secondary-text-color)',
    cursor: 'pointer',
    padding: '2px',
    display: 'flex',
    alignItems: 'center',
  },
  collapsedSummary: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 12px',
    cursor: 'pointer',
  },
  summaryText: {
    fontSize: '0.75rem',
    color: 'var(--secondary-text-color)',
    fontFamily: "'Space Mono', monospace",
  },
  editHint: {
    fontSize: '0.7rem',
    color: 'var(--accent-color)',
    opacity: 0.6,
  },
  addBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    margin: '0 20px 16px',
    padding: '10px',
    background: 'transparent',
    border: '1px dashed var(--border-color)',
    borderRadius: '8px',
    color: 'var(--secondary-text-color)',
    cursor: 'pointer',
    fontSize: '0.85rem',
    fontFamily: 'inherit',
    transition: 'border-color 0.2s, color 0.2s',
  },
  testConnectionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
    marginTop: '2px',
  },
  testBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    padding: '6px 12px',
    border: '1px solid var(--border-color)',
    borderRadius: '6px',
    background: 'transparent',
    color: 'var(--secondary-text-color)',
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontFamily: 'inherit',
    fontWeight: 500,
    transition: 'border-color 0.2s, color 0.2s, background 0.2s',
  },
  testBtnDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  testBtnOk: {
    borderColor: '#34A853',
    color: '#34A853',
    background: 'rgba(52, 168, 83, 0.08)',
  },
  testBtnFail: {
    borderColor: '#EA4335',
    color: '#EA4335',
    background: 'rgba(234, 67, 53, 0.08)',
  },
  testErrorText: {
    fontSize: '0.72rem',
    color: '#EA4335',
    maxWidth: '260px',
  },
  infoBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    fontSize: '0.72rem',
    color: 'var(--secondary-text-color)',
    borderTop: '1px solid var(--border-color)',
    background: 'rgba(255,255,255,0.01)',
  },
};
